name: 'finely'

services:
  api:
    build:
      context: ./api
    image: ghcr.io/orguetta/finely-api:latest
    container_name: finely_api
    command: sh -c "make run"
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - migrate
      - db
    networks:
      - internal
      - proxy
    restart: always

  migrate:
    build:
      context: ./api
    image: ghcr.io/orguetta/finely-migrate:latest
    container_name: finely_migrate
    working_dir: /app
    entrypoint: ["sh", "./entrypoint.migrate.sh"]
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings.dev
    depends_on:
      - db
    networks:
      - internal

  web:
    build:
      context: ./web
    image: ghcr.io/orguetta/finely-web:latest
    container_name: finely_web
    ports:
      - "5173:80"
    depends_on:
      - api
    networks:
      - internal
      - proxy
    restart: always

  landing:
    build:
      context: ./landing
    image: ghcr.io/orguetta/finely-landing:latest
    container_name: finely_landing
    ports:
      - "5174:3000"
    depends_on:
      - api
    networks:
      - proxy
    restart: always
  db:
    image: postgres:16-alpine
    container_name: finely_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env.dev
    networks:
      - internal
    restart: always 

volumes:
  postgres_data:

networks:
  internal:
    internal: true
  proxy:
    external: true